// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip boom;
        public static AudioClip electrooff;
        public static AudioClip factorybg;
        public static AudioClip Gulp;
        public static AudioClip liftping;
        public static AudioClip liftping1;
        public static AudioClip littleBoom;
        public static AudioClip looting;
        public static AudioClip MainMenu;
        public static AudioClip packost;
        public static AudioClip pickup;
        public static AudioClip press;
        public static AudioClip request;
        public static AudioClip sfxlift;
        public static AudioClip sfxliftopn;
        public static AudioClip step;
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip load;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip positive;
        public static AudioClip save;
        public static AudioClip sharp_echo;
        public static AudioClip Wrong_Error;
    }

    public static void InitAudio()
    {
        Audio.boom = Resources.Load<AudioClip>("Audio/boom");
        Audio.electrooff = Resources.Load<AudioClip>("Audio/electrooff");
        Audio.factorybg = Resources.Load<AudioClip>("Audio/factorybg");
        Audio.Gulp = Resources.Load<AudioClip>("Audio/Gulp");
        Audio.liftping = Resources.Load<AudioClip>("Audio/liftping");
        Audio.liftping1 = Resources.Load<AudioClip>("Audio/liftping1");
        Audio.littleBoom = Resources.Load<AudioClip>("Audio/littleBoom");
        Audio.looting = Resources.Load<AudioClip>("Audio/looting");
        Audio.MainMenu = Resources.Load<AudioClip>("Audio/MainMenu");
        Audio.packost = Resources.Load<AudioClip>("Audio/packost");
        Audio.pickup = Resources.Load<AudioClip>("Audio/pickup");
        Audio.press = Resources.Load<AudioClip>("Audio/press");
        Audio.request = Resources.Load<AudioClip>("Audio/request");
        Audio.sfxlift = Resources.Load<AudioClip>("Audio/sfxlift");
        Audio.sfxliftopn = Resources.Load<AudioClip>("Audio/sfxliftopn");
        Audio.step = Resources.Load<AudioClip>("Audio/step");
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/Engine/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/Engine/MouseInButton");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/Engine/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/Engine/PanelOut");
        Audio.click = Resources.Load<AudioClip>("Audio/Engine/Bank/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/Engine/Bank/click_2");
        Audio.load = Resources.Load<AudioClip>("Audio/Engine/Bank/load");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/Engine/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/Engine/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/Engine/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/Engine/Bank/misc_sound");
        Audio.negative = Resources.Load<AudioClip>("Audio/Engine/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/Engine/Bank/negative_2");
        Audio.positive = Resources.Load<AudioClip>("Audio/Engine/Bank/positive");
        Audio.save = Resources.Load<AudioClip>("Audio/Engine/Bank/save");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/Engine/Bank/sharp_echo");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/Engine/Bank/Wrong Error");
    }
}
